server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://106.14.3.196:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qwer2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true